services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/report_generator_db
      - SPRING_DATASOURCE_USERNAME=report_user
      - SPRING_DATASOURCE_PASSWORD=report_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=report_generator_db
      - POSTGRES_USER=report_user
      - POSTGRES_PASSWORD=report_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  downloads: